<?php
return [
    1000=>"Token err : The userId is Required",
    1001=>"Token err : The cid is Required",
    1002=>"Token err : the siteId is Required",
    1003=>"Token err : The accessKey is Required",
    1004=>"Token err : The siteKey is Required",
    1005=>"Token err : The policy is Required",
    1006=>"PlaybackPolicy : The limit should be boolean",
    1007=>"PlaybackPolicy : The persistent should be boolean",
    1008=>"PlaybackPolicy : The duration should be number",
    1011=>"PlaybackPolicy : The expireDate time format should be 'YYYY-MM-DD'T'HH:mm:ss'Z'",
    1019=>"ExternalKey : The mpegCenc should be array.",
    1020=>"ExternalKey : The hlsAes should be array.",
    1040=>"MpegCenc : The KeyId should be 16byte hex String",
    1041=>"MpegCenc : The Key should be 16byte hex String",
    1042=>"MpegCenc : The Iv should be 16byte hex String",
    1044=>"hlsAes : The Key should be 16byte hex String",
    1045=>"hlsAes : The Iv should be 16byte hex String",
    1047=>"Ncg : The Cek should be 32byte hex String",
    1101=>"SecurityPolicy : The widevine securityLevel should be integer",
    1102=>"SecurityPolicy : The playready securityLevel should be integer",
    1103=>"SecurityPolicy : The playready digitalVideoProtectionLevel should be integer",
    1104=>"SecurityPolicy : The playready analogVideoProtectionLevel should be integer",
    1105=>"SecurityPolicy : The playready compressedDigitalAudioProtectionLevel should be integer",
    1106=>"SecurityPolicy : The playready uncompressedDigitalAudioProtectionLevel should be integer",
    1107=>"SecurityPolicy : The playready requireHdcpType1 should be boolean",
    1108=>"SecurityPolicy : The fairplay hdcpEnforcement should be integer",
    1109=>"SecurityPolicy : The fairplay allowAirplay should be boolean",
    1110=>"SecurityPolicy : The fairplay allowAvAdapter should be boolean",
    1111=>"SecurityPolicy : The ncg allowMobileAbnormalDevice should be boolean",
    1112=>"SecurityPolicy : The ncg allowExternalDisplay should be boolean",
    1113=>"SecurityPolicy : The ncg controlHdcp should be integer",
];
